# Generated by Django 5.0.4 on 2024-05-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('launch', models.IntegerField()),
                ('edition', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('year_edition', models.IntegerField()),
                ('edition_number', models.IntegerField()),
            ],
        ),
    ]
