# Generated by Django 5.0.4 on 2024-05-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='type',
            new_name='book_type',
        ),
    ]
